### ISSUE TITLE
Not included in core

### ISSUE THREAD

**Issue by josephdadams** [bitfocus/companion-module-dalite-scb#1]
@Santana1053 This module is not in either the backport 1.4 branch or the master 2.0 branch. How is it coming along? Is it ready to be included?

**Comment by Magi1053** [comment]
I'll try to get this polished later next week. The current code is fully functional and I've been using it in production for the past several months. All that's missing are a few extra features and documentation.

**Comment by Santana1053** [comment]
I'll try to get this polished later next week. The current code is fully functional and I've been using it in production for the past several months. All that's missing are a few extra features and documentation.

**Comment by josephdadams** [comment]
It's in the master branch as well as the backport branch now. Do you want me to close this or leave it open?
